/**
 * Created by wgw on 2016/2/13.
 */


//参与者-自控框-属性
var GAME_STRUCT_CLIENT_SELF_CONTROL_X = 100;
var GAME_STRUCT_CLIENT_SELF_CONTROL_Y = 400;
var GAME_STRUCT_CLIENT_SELF_CONTROL_W = 700;
var GAME_STRUCT_CLIENT_SELF_CONTROL_H = 150;
