/**
 * Created by wgw on 2016/2/13.
 */

    //参与者-消息展示框-属性
    var GAME_STRUCT_CLIENT_MSG_SHOW_X = 100;
    var GAME_STRUCT_CLIENT_MSG_SHOW_Y = 50;
    var GAME_STRUCT_CLIENT_MSG_SHOW_W = 700;
    var GAME_STRUCT_CLIENT_MSG_SHOW_H = 300;

    //参与者-自控框-属性
    var GAME_STRUCT_CLIENT_SELF_CONTROL_X = 100;
    var GAME_STRUCT_CLIENT_SELF_CONTROL_Y = 400;
    var GAME_STRUCT_CLIENT_SELF_CONTROL_W = 700;
    var GAME_STRUCT_CLIENT_SELF_CONTROL_H = 150;

    //参与者-成员框-属性
    var GAME_STRUCT_CLIENT_MEM_LIST_X = 820;
    var GAME_STRUCT_CLIENT_MEM_LIST_Y = 50;
    var GAME_STRUCT_CLIENT_MEM_LIST_W = 200;
    var GAME_STRUCT_CLIENT_MEM_LIST_H = 500;